nparts = 1
NCPUs = 4
Vp = 2750.0
Vs = 0.0
Vmax = 5000.0
rho = 2000.0
frequency = 0.015
duration = 1000.0
dxz = 10000.0
inflat = 0.44
source_element = 3
receiver_elements = [0, 1, 2, 3, 4, 5, 6, 7, 8]
order_b2 = 7
order_b1 = 7
gauss_order = 6
delta_t = 0.1
time_steps = 18000
ppw = 5.0
rads = [600000.0, 1221500.0, 1700000.0]
Model = "uniform"
model_file = "/global/homes/m/mgawan/dfdm_current/solver/config/ak135f.model"
